tahapan-tahapan :
    1. preproses data/feuture Engineering
    2. train data
    3. test data

preproses data/feuture Engineering:

A. Clean data 
    1. menghilangkan karakter-karakter kata yang dianggap tdk penting dan Punctuation (Special character cleaning)
    2. mengubah kata-kata menjadi lowercase (Upcase/downcase)
    3. menghilangkan kata-kata yg tidak penting (stopword)
    4. mengembalikan kata-kata kedalam bentuk asli nya nya (Stemming/Lemmatization)
    5. mengkoreksi beberapa kata (typo correction)
    
B. Text representation
    1. Word Count Vectors : menghitung setiap jumlah kata/corpus yg muncul dalam kumpulan data tersebut
    2. TF–IDF Vectors : menghitung jarak kata antar kata dengan rumus yg telah di tentukan tanpa memperhitungkan urutan.
    3. Word Embeddings : setiap kata yang muncul akan dihitung kedekatan nya dengan kata yg disekitar nya
    4. Text based or NLP based features : membuat secara manual fitur2 yang akan digunakan, misal menggabungkan antar perhitungan jumlah kata, jarak antar kata, kedudukan sebuah kata, atau pun sifat dari kata tersebut (post tagger)
    5. Topic Models : dalam setiap kumpulan data di lihat secara probability kata yang paling dominan

In [96]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
#nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords

In [97]:
movie_data = load_files(r"E:\txt_sentoken")
X, y = movie_data.data, movie_data.target

Text Preprocessing

In [98]:
documents = []

from nltk.stem import WordNetLemmatizer

stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

In [99]:
documents[0]

'arnold schwarzenegger ha been an icon for action enthusiast since the late 80 but lately his film have been very sloppy and the one liner are getting worse nit hard seeing arnold a mr freeze in batman and robin especially when he say ton of ice joke but hey he got 15 million what it matter to him nonce again arnold ha signed to do another expensive blockbuster that can compare with the like of the terminator series true lie and even eraser nin this so called dark thriller the devil gabriel byrne ha come upon earth to impregnate woman robin tunney which happens every 1000 year and basically destroy the world but apparently god ha chosen one man and that one man is jericho cane arnold himself nwith the help of trusty sidekick kevin pollack they will stop at nothing to let the devil take over the world nparts of this are actually so absurd that they would fit right in with dogma nyes the film is that weak but it better than the other blockbuster right now sleepy hollow but it make the wo

# Converting Text to Numbers

Finding TFIDF

In [100]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [101]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [102]:
y

array([0, 1, 1, ..., 1, 0, 0])

Training and Testing Sets

In [103]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [104]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [105]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 7, 0],
       [0, 0, 1, ..., 0, 1, 0]], dtype=int64)

Training Text Classification Model and Predicting Sentiment

In [106]:
from sklearn.ensemble import RandomForestClassifier

In [107]:
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(X_train, y_train) 

RandomForestClassifier(n_estimators=1000, random_state=0)

In [108]:
y_pred = classifier.predict(X_test)

In [109]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,

In [110]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[173  35]
 [ 20 172]]
              precision    recall  f1-score   support

           0       0.90      0.83      0.86       208
           1       0.83      0.90      0.86       192

    accuracy                           0.86       400
   macro avg       0.86      0.86      0.86       400
weighted avg       0.86      0.86      0.86       400

0.8625


# data bahasa indo 

In [111]:
import pandas as pd
data = pd.read_csv("data.csv", delimiter=";", encoding = 'iso-8859-1')
data.tail()

label                                           sentence
5995  positive                                              bagus
5996  positive                                        keren mvnya
5997  positive  untuk seseorang yang sedang bersamaku terimaka...
5998  positive                      luar biasa mental illness nya
5999  positive                        sibuk jatuh cinta sendirian

In [112]:
x_new = list(data['sentence'])

In [113]:
data['label_id'] = data['label'].factorize()[0]
from io import StringIO
kategori_id_data = data[['label', 'label_id']].drop_duplicates().sort_values('label_id')
kategori_to_id = dict(kategori_id_data.values)
id_to_kategori = dict(kategori_id_data[['label_id', 'label']].values)

In [114]:
id_to_kategori

{0: 'negative', 1: 'neutral', 2: 'positive'}

In [136]:
data

label                                           sentence  label_id
0     negative  belum bisa membaca flazz di kartu paspor domestik         0
1     negative  aplikasi jelek programmer memprogram aplikasi ...         0
2     negative                 setelah di update belum bisa login         0
3     negative              koneksi terputus belum bisa transaksi         0
4     negative                               aplikasi susah login         0
...        ...                                                ...       ...
5995  positive                                              bagus         2
5996  positive                                        keren mvnya         2
5997  positive  untuk seseorang yang sedang bersamaku terimaka...         2
5998  positive                      luar biasa mental illness nya         2
5999  positive                        sibuk jatuh cinta sendirian         2

[6000 rows x 3 columns]

In [135]:
import numpy as np
y_list = list(data['label_id'])
y_new = np.array(y_list)

In [116]:
y_new

array([0, 0, 0, ..., 2, 2, 2])

In [117]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(x_new, y_new, random_state = 0)

In [118]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [119]:
clf = MultinomialNB().fit(X_train_tfidf, y_train)

In [120]:
a = count_vect.transform(X_test)
X_coba = tfidf_transformer.fit_transform(a).toarray()

y_pred = clf.predict(X_coba)

In [121]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[380  49  65]
 [ 70 316 105]
 [ 49  49 417]]
              precision    recall  f1-score   support

           0       0.76      0.77      0.77       494
           1       0.76      0.64      0.70       491
           2       0.71      0.81      0.76       515

    accuracy                           0.74      1500
   macro avg       0.75      0.74      0.74      1500
weighted avg       0.74      0.74      0.74      1500

0.742


In [137]:
test =['hari ini sangat indah',
       'kok kamu jelek bgt sih',
       'ada berita duka nih hari ini',
       'bagaimana kabar hari ini?',
       'semua baik-baik2 saja kan',
      'bagaimana dengan perasaan kamu hari ini?',
      'kabar jogja hari ini',
      'kapan corona nya pergi']

In [123]:
for i in test :
    a = count_vect.transform([i])
    X_coba = tfidf_transformer.fit_transform(a).toarray()
    y_pred = clf.predict(X_coba)
    if y_pred[0]== 0 :
        label = 'negative'
    elif y_pred[0]== 1 :
        label = 'neutral'
    else :
        label = 'positive'
    print ({"teks": i , "label" : label})


{'teks': 'hari ini sangat indah', 'label': 'positive'}
{'teks': 'kok kamu jelek bgt sih', 'label': 'negative'}
{'teks': 'ada berita duka nih hari ini', 'label': 'negative'}
{'teks': 'bagaimana kabar hari ini?', 'label': 'neutral'}
{'teks': 'semua baik-baik2 saja kan', 'label': 'positive'}
{'teks': 'bagaimana dengan perasaan kamu hari ini?', 'label': 'positive'}
{'teks': 'kabar jogja hari ini', 'label': 'positive'}
{'teks': 'kapan corona nya pergi', 'label': 'neutral'}


# deep learning

In [124]:
import numpy as np
import pandas as pd 
from keras import initializers
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, Dropout, LSTM
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
#import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
#import seaborn as sns
import xlsxwriter
from keras.models import load_model
from keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout, Flatten, MaxPooling1D, Input, Concatenate

Using TensorFlow backend.


In [125]:
data = pd.read_csv("data.csv", delimiter=";", encoding = 'iso-8859-1')
data.tail()

label                                           sentence
5995  positive                                              bagus
5996  positive                                        keren mvnya
5997  positive  untuk seseorang yang sedang bersamaku terimaka...
5998  positive                      luar biasa mental illness nya
5999  positive                        sibuk jatuh cinta sendirian

In [126]:
data['label_id'] = data['label'].factorize()[0]
from io import StringIO
kategori_id_data = data[['label', 'label_id']].drop_duplicates().sort_values('label_id')
kategori_to_id = dict(kategori_id_data.values)
id_to_kategori = dict(kategori_id_data[['label_id', 'label']].values)

In [127]:
id_to_kategori

{0: 'negative', 1: 'neutral', 2: 'positive'}

In [128]:
leng = kategori_id_data.label_id.values
leng = len (leng)
leng

3

# Pembentukan Model

sumber model : https://github.com/diegoschapira/CNN-Text-Classifier-using-Keras/blob/master/models.py

Deep CNN

In [129]:
def get_model(X, Y):
    model = Sequential()
    model.add(Embedding(input_dim = vocab, output_dim = 128, input_length = max_sentence_length, embeddings_initializer = initializer))
    model.add(Conv1D(128, 7, activation='relu',padding='same'))
    model.add(MaxPooling1D())
    model.add(Conv1D(256, 5, activation='relu',padding='same'))
    model.add(MaxPooling1D())
    model.add(Conv1D(512, 3, activation='relu',padding='same'))
    model.add(MaxPooling1D())
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(leng, activation='softmax'))
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    model.summary()
    
    return model

def evaluation(model, X, Y):
    Y_pred = model.predict(X)
    Y_pred_class = np.argmax(Y_pred, axis=1)
    Y_act = Y
    
    acc = accuracy_score(Y_act, Y_pred_class)
    
    return acc

In [130]:
text1 = data['sentence'].values
label = data['label_id'].values

In [131]:
#text1 = str(text1)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text1)

vocab = max([len(tokenizer.word_index)]) + 1 # kamus kata 
max_sentence_length = 100 # panjang kalimat
batch_size = 32 # penentuan jumlah sampel yang ditraining pada tiap epoch
num_epochs = 10 # banyak iterasi pada saat training model 
initializer = initializers.RandomUniform(minval=-0.05, maxval=0.05, seed=2) # mengatur angka random weigth
embedding_dim = 300

In [132]:
#Data Train
X = tokenizer.texts_to_sequences(text1)
X = pad_sequences(X, maxlen=max_sentence_length)
Y = to_categorical(label, num_classes = leng)

In [133]:
model = get_model(X, Y)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 128)          1369728   
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 100, 128)          114816    
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 50, 128)           0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 50, 256)           164096    
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 25, 256)           0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 25, 512)           393728    
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 12, 512)          

In [134]:
# training model
model.fit(X, Y, batch_size=batch_size, epochs=num_epochs, verbose=1)

e:\nilam titip\envs\env_dev\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/10
6000/6000 [==============================] - 140s 23ms/step - loss: 1.0146 - accuracy: 0.4660
Epoch 2/10
6000/6000 [==============================] - 132s 22ms/step - loss: 0.6828 - accuracy: 0.7283
Epoch 3/10
6000/6000 [==============================] - 122s 20ms/step - loss: 0.3182 - accuracy: 0.8880
Epoch 4/10
6000/6000 [==============================] - 164s 27ms/step - loss: 0.1369 - accuracy: 0.9603
Epoch 5/10
6000/6000 [==============================] - 165s 28ms/step - loss: 0.0659 - accuracy: 0.9798
Epoch 6/10
6000/6000 [==============================] - 157s 26ms/step - loss: 0.0511 - accuracy: 0.9867
Epoch 7/10
6000/6000 [==============================] - 154s 26ms/step - loss: 0.0460 - accuracy: 0.9892
Epoch 8/10
6000/6000 [==============================] - 137s 23ms/step - loss: 0.0373 - accuracy: 0.9890
Epoch 9/10
6000/6000 [==============================] - 143s 24ms/step - loss: 0.0234 - accuracy: 0.9923
Epoch 10/10
6000/6000 [==============================] 

# Akurasi

In [138]:
acc = evaluation(model, X, label)
print("Accuracy: %.2f" % (acc*100), "%")

Accuracy: 99.45 %


Menyimpan model dan memanggil model

In [ ]:
model.save('model_Deep_CNN.h5')

In [ ]:
model = load_model('model_Deep_CNN.h5')

# Testing Data yang baru

In [ ]:
test =['hari ini sangat indah',
       'kok kamu jelek bgt sih',
       'ada berita duka nih hari ini',
       'bagaimana kabar hari ini?',
       'semua baik-baik2 saja kan']

In [ ]:
text1 = tokenizer.texts_to_sequences(test)

In [ ]:
text1 = pad_sequences(text1, maxlen=max_sentence_length)

In [ ]:
pred_label = model.predict(text1)
label1 = np.argmax(pred_label, axis = 1) 
ynew = model.predict_proba(text1)
prob = ynew.max(axis=1)

In [ ]:
label =[]
kal = []
probab = []
for unlabeled, label1, prob in zip(test, label1, prob):
    print('"{}"'.format(unlabeled))
    u = unlabeled
    l = id_to_kategori[label1]
    label.append(l)
    kal.append(u)
    probab.append(prob)
    
    print("  - Prediksi: '{}'".format(id_to_kategori[label1]))
    print("  - Probab: '{}'".format(prob))
    print("")

#print (label)
#print (kal)
#hasil =pd.DataFrame({"Descript" : kal, "Category" : label, "probab" : probab})
#print (hasil)